version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: ruhullah
      POSTGRES_PASSWORD: 1234567890aA@

  web:
    build:
      context: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 todo.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=todo.settings
