# Generated by Django 4.2.7 on 2023-11-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_completed',
            new_name='status',
        ),
    ]
